### ISSUE TITLE
預設data path 的位置

### ISSUE THREAD

**Issue by lmc6130** [AxotZero/esun_sar_baseline#1]
Hi
想請問如何設定自己的data path。因為在config.json裡面，每次重跑程式，num_cat_pkl_path都會是預設的路徑，想請問相關function的設定在哪裡？謝謝。

**Comment by AxotZero** [comment]
你好，想問下你的狀況是否是：

1. 改完config.json的路徑
2. 執行 train_5fold.sh
3. 在初始化模型時，發現 path 沒有改變嗎?

**Comment by lmc6130** [comment]
您好，是的。改了config但跑的時候config沒變。

**Comment by AxotZero** [comment]
你好，我剛剛試了修改路徑並沒有出現問題，
若是還是一樣的話可以在 `src/model/model.py` 修改。
```python=
class SarModel(BaseModel):
    def __init__(self,
                 num_cat_pkl_path="", emb_feat_dim=32, hidden_size=128, hidden_size_coeff=6, dropout=0.3,
                 max_len=512,
                 temporal_aggregator_type="TemporalTransformerAggregator", temporal_aggregator_args={},
                 ):
        super().__init__()
        num_cat_dict = load_yaml("YOUR_PATH")
        ....
```

**Comment by lmc6130** [comment]
你好，非常感謝您的協助！

**Comment by YU-SHAO-XU** [comment]
你好 
想請問 train 過程中也會有類似問題
FileNotFoundError: [Errno 2] No such file or directory: '/media/hd03/axot_data/sar/data/num_cat_dict.yml'
但已經有建立 資料夾並放num_cat_dict.yml於資料夾內 我可以怎麼做呢 謝謝
